name: Node & npm setup
description: 'Common job setup for npm managed repo'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 20

    - name: Install npm
      shell: bash
      run: npm install -g npm@11.5.2

    - name: Install dependencies
      shell: bash
      run: npm ci
